@posts = http://localhost:3000/api/posts

###
GET {{posts}}

###
GET {{posts}}?$filter=id eq 1
###
GET {{posts}}?$filter=contains(caption, 'play')
###
GET {{posts}}?$filter=user_id eq 1 and contains(caption, 'one')




